name: CI - ivy-roots

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # --- PHP Setup ---
    - name: Setup PHP 8.3
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3
        tools: composer:v2

    - name: Show PHP version
      run: php -v

    # --- Composer ---
    - name: Validate composer.json
      run: composer validate --strict

    - name: Cache Composer packages
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-8.3-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-8.3-

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Verify Composer dependencies
      run: composer check-platform-reqs

    # --- PHPStan ---
    - name: Run PHPStan
      uses: php-actions/phpstan@v3
      with:
        path: src/
        php_version: 8.3
        level: 1

    # --- Tests (commented out) ---
    # - name: Run tests
    #   run: vendor/bin/pest
