name: PHP CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Setup PHP 8.3
      - name: Setup PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer:v2

      # Show PHP version
      - name: Show PHP version
        run: php -v

      # Validate composer.json
      - name: Validate composer.json
        run: composer validate --strict

      # Cache Composer packages
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-php-

      # Install dependencies (no lock file)
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      # Verify PHP platform requirements
      - name: Check platform requirements
        run: composer check-platform-reqs

      # Run PHPStan
      - name: Run PHPStan
        run: vendor/bin/phpstan analyse src/ --level=1

      # Optional: run tests (commented out until you add them)
      #- name: Run Pest tests
      #  run: vendor/bin/pest
